---
title: "Reflective and intuitive thinking styles"
description: |
  A new construct on the block for employee selection and development? 
preview: ./intuition_vs_reason.jpg
author:
  - name: Luděk Stehlík
    url: https://www.linkedin.com/in/ludekstehlik/
date: 12-12-2023
categories:
  - meta-analysis
  - performance
  - employee selection
  - employee development
  - psychometrics
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 2
    toc_float: true
    code_folding: true
---

[Alaybek et al. (2021)](https://onlinelibrary.wiley.com/doi/full/10.1111/peps.12443){target="_blank"} quite recently conducted a meta-analysis examining the relations between individual differences in reflective (rational) and intuitive thinking styles and workplace task performance, and showed that reflective thinking style has a positive and non-zero relation with task performance (*ρ* = 0.213). 

This positive relation was stronger in environments characterized by higher task complexity, greater importance of creativity and innovation for work tasks, and higher time pressure associated with work tasks. 

In the case of intuitive thinking style, there was a very small but positive relation with task performance (*ρ* = 0.051), and this relation was stronger in environments characterized by higher task complexity. 

More important, incremental validity analyses revealed that reflective thinking style explains unique variance in task performance, beyond conscientiousness and intelligence. 

It seems that a reflective thinking style may bear some extra clues to workplace performance. Not super surprising, but still far away from “Elementary, my dear Watson!" 😉

