---
title: "Evidence-based interventions that help reduce the gender pay gap"
description: |
 Pay inequality between men and women is not only an ethical and legal issue for companies, but also a marketing issue - it can have a negative impact on their "employer brand" and attractiveness as an employer. This means that if companies want to attract and retain talented employees, they must be able to ensure that they treat men and women equally in this respect. Let's look at what the existing evidence tells us about what might help us with this.
preview: ./genderPayGap.jpg
author:
  - name: Luděk Stehlík
    url: https://www.linkedin.com/in/ludekstehlik/
date: 11-18-2022
categories:
  - gender pay gap
  - evidence-based management
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 2
    toc_float: true
    code_folding: true
---

If you are responsible for DEI initiatives in your company, you might be interested in a paper by [The Behavioural Insights Team](https://www.bi.team/) that lists several possible interventions to close the gender pay gap, divided into three categories based on the extent to which their effectiveness is supported by empirical evidence.

🥇 **Actions with well-documented effectiveness:**

* Including more women on shortlists in recruitment and promotion.
*️ Use of tasks assessing job skill levels in the selection of new employees.
* Use of structured interviews in recruitment and promotion.
* Encouraging salary negotiation through disclosure of existing salary ranges.
* Introducing transparent promotion and reward processes.
* Appointing a manager or establishing a corporate diversity task force.

🥈 **Potentially promising actions, but requiring further evidence of their effectiveness:**

* Increasing work flexibility for men and women.
* Supporting shared parental leave.
* Recruiting former employees who have had to interrupt their careers for a prolonged period for various personal reasons.
* Offering mentoring and sponsorship.
* Offering networking programs.
* Setting internal targets.

🥉 **Actions with mixed evidence of their effectiveness:**

* Training on the topic of unconscious bias.
* Diversity training.
* Leadership development training.
* Demographically diverse selection panels in external and internal recruitment.

For those interested, here is the original document for a closer look.

<object data="Gender-Pay-Gap-actions.pdf" type="application/pdf" height="400px">
    <embed src="Gender-Pay-Gap-actions.pdf">
        <p>This browser does not support PDF files. Please download the PDF file to view it: <a href="Gender-Pay-Gap-actions.pdf">Download PDF</a>.</p>
    </embed>
</object>
<br>


A final note. As useful as it is to know which interventions have a decent chance of reducing gender pay inequality, an integral part of this fight is to regularly check the existence of this inequality across the organisation and within different types of organisational processes. As [Alessandro Linari](https://www.linkedin.com/in/alezzandro/) aptly noted in a discussion on Linkedin, "*The best way to keep the gender pay gap under control is still to do a periodic pay equity analysis across the organisation and address any identified gap. I say unfortunately because there are a thousand different ways where pay differences still manage to sneak into the workforce, through hiring and promotion practices, but also retention policies, bonus allocation, performance management, and others.*" If you want to learn more about some of the technical details of such an analysis, check out [one of my previous posts on this topic](https://blog-about-people-analytics.netlify.app/posts/2021-01-29-paygap/) (unfortunately, it is now only available in Czech, but you can use one of the online translators to get around this limitation 😉).