---
title: "Do high-low range goals aid in maintaining motivation over time?"
description: |
  Is there enough evidence to bet on this technique and give it a try? 
preview: ./goals.jpg
author:
  - name: Luděk Stehlík
    url: https://www.linkedin.com/in/ludekstehlik/
date: 12-29-2023
categories:
  - goal setting
  - resolution
  - motivation
  - persistence
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 2
    toc_float: true
    code_folding: true
---

Being at the time of year when [the "fresh start" effect](https://faculty.wharton.upenn.edu/wp-content/uploads/2014/06/Dai_Fresh_Start_2014_Mgmt_Sci.pdf){target="_blank"} can help with achieving goals, like many, I'm contemplating what goals to set for the upcoming year and exploring strategies to enhance their attainability.

Recently, I encountered a suggestion to establish high-low range goals rather than single-number targets. For example, aiming to run 8-12 km per week instead of a fixed 10 km. This approach is thought to offer a balanced mix of attainability and challenge, potentially leading to a greater feeling of accomplishment and, more importantly, a higher likelihood of goal re-engagement, i.e. sustained motivation to continue with one's goals over time.

This all makes pretty good sense, yet I was surprised to find scant research on this topic, particularly outside the context of weight loss (see, for example, [the Scott & Nowlis' 2013 study](https://psycnet.apa.org/record/2013-32845-004){target="_blank"}). Maybe I was just looking in the wrong places, or using the wrong key terms. Does anyone have insights into relevant research from other fields, or have you experimented with this approach in your organization?

However, given the low-stakes circumstances, the minimal investment required, the consistency of the technique with existing knowledge about human motivation and common sense, and the low likelihood of serious adverse effects, I think it is quite reasonable to bet on this particular technique and give it a try, even though there seems to be relatively little evidence available.