---
title: "Another positive effect of mindfulness meditation on the horizon?"
description: |
  Is it possibile to improve the objectivity of decision making through mindfulness meditation? 
preview: ./spock.jpg
author:
  - name: Luděk Stehlík
    url: https://www.linkedin.com/in/ludekstehlik/
date: 06-05-2023
categories:
  - decision-making
  - mindfulness
  - field experiment
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 2
    toc_float: true
    code_folding: true
---

Maybe, at least this is suggested by a pre-registered field experiment by [Ash et al. (2023)](https://www.sciencedirect.com/science/article/pii/S0165176523000228?via%3Dihub+){target="_blank"}, where people practicing [mindfulness meditation](https://en.wikipedia.org/wiki/Mindfulness){target="_blank"} for 15 minutes a day for 2 weeks compared to an active control (listening to relaxing music) showed a reduced tendency to avoid painful information that may trigger worry or regret, with a likely mechanism for this effect being improved emotion regulation.

If this were the case, this would be great news for our decision making, as the ability to impartially evaluate all relevant information is one of the keys to good decision making. 

It's true that the observed effect was rather small and barely distinguishable from noise and we may be concerned about its reproducibility, but as a Trekkie and a big fan of Mr. Spock, I like the idea that there might be a method that could make us a little more like this cool half-Vulcan and half-human 😉🖖



