---
title: "About this blog"
description: |
  Exploring People Analytics topics using R & Python
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Based on advice from more experienced colleagues from data-science community ([Matt Dancho](https://www.linkedin.com/in/mattdancho/) and [Keith McNulty](https://www.linkedin.com/in/keith-mcnulty/), to name but a few) I have decided to set up my own blog so that I can at least partially give back to others what I have learned myself through the blogging of others. Besides that it also give me an opportunity - and indeed a bit of an excuse - to explore and try new things related to People analytics and to better organize my thoughts about this subject.

On this blog, I plan to publish articles (both in Czech and English) that will be more about technical and analytical aspects of People analytics, nevertheless, I will always try to present individual topics in the context of practical issues that keep busy all those HR professionals who want to enhance not just *efficiency* but also *effectiveness* of HR processes in organizations. In general, my goal is to promote the idea that when critical thinking, hard (i.e., reliable, valid and relevant) data and their rigorous analysis are combined, organizations have a much more better chance of achieving their goal, be it more productive workforce or more satisfied and happy employees.

The views and attitudes presented on this blog are just my own and do not necessarily reflect the official views and attitudes of any of my current or former employers.

---

Dal jsem na radu zkušenějších (za všechny zmiňme např. [Matta Dancha](https://www.linkedin.com/in/mattdancho/) a [Keitha McNultyho](https://www.linkedin.com/in/keith-mcnulty/)) a založil jsem si svůj vlastní blog, abych mohl jednak alespoň částečně vrátit druhým to, co jsem se sám díky blogům druhých naučil, ale také abych měl příležitost - a vlastně tak trochu i záminku - zkoumat a zkoušet si různé nové věci týkající se HR analytiky a tříbit si při tom zároveň své myšlenky.

Na tomto blogu plánuji uveřejňovat články (v češtině i angličtině), které se budou více zabývat technickou a analytickou stránkou HR analytiky, zároveň se ale budu vždy snažit prezentovat jednotlivá témata v kontextu praktických problémů a otázek, které trápí všechny ty, co se snaží zvýšit nejen efektivitu (*efficiency*), ale také účinnost (*effectiveness*) HR procesů ve firmách a organizacích. Obecně je mým cílem propagovat myšlenku, že když se spojí kritické myšlení, tvrdá (čti spolehlivá, validní a relevantní) data a jejich pečlivá analýza, mají organizace větší šanci na dosažení svých cílů, ať už jsou jimi vyšší produktivita zaměstnanců nebo jejich větší spokojenost a štěstí. 

Názory a postoje prezentované na tomto blogu jsou pouze mé vlastní, a nemusí tak tedy nutně odrážet oficiální názory a postoje žádného z mých současných nebo bývalých zaměstnavatelů.