---
title: 'Can a simple coin flip help you decide and avoid overanalyzing?'
description: |
  We all, at least occasionally, find ourselves stuck between two options - endlessly weighing the pros and cons, searching for additional information, or asking everyone around us for advice.      
preview: ./coin_flip_experiment1.png    
author:
  - name: Luděk Stehlík
    url: https://www.linkedin.com/in/ludekstehlik/
date: 10-29-2025
categories:
  - decision making 
  - behavioral science 
  - cognitive science
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 2
    toc_float: true
    code_folding: true
---

Research by [Douneva et al. (2019)](https://www.sciencedirect.com/science/article/pii/S0022103118303950){target="_blank"} suggests there might be a surprisingly simple decision aid to help us move forward: a coin flip 🪙

Across five experiments with nearly 1,000 participants, people who flipped a coin between preliminary and final decision - whether about renewing a manager’s contract, choosing a product, or donating to a charity - showed less need to keep gathering more information compared to those who didn’t.️

* Effect sizes were small to moderate, but pretty consistent across different decision types and samples.️
* Participants didn’t just blindly follow the coin’s outcome - they usually stuck with their original preference as much as or even more than the control group, suggesting that the decision aid didn't determine the decision outcome.️
* The coin didn’t make decisions more/less accurate, even when there was an objectively correct answer, but it made people feel ready to decide.

What might be happening behind the scenes? The authors connect the effect to well-established psychological theories:

1. Choice Closure: Flipping a coin acts like a mental “stop sign” - a psychological closure cue. It signals that the deliberation phase is over, cutting the urge to keep collecting more data.
2. Mindset Transition: The coin flip nudges people from a deliberative mindset (weighing options) to an implemental one (gearing up for action).
3. It might also help people tune into their “gut feeling” by forcing an emotional reaction to a specific outcome.

Curious if anyone here has experience with this specific decision aid and how it works for them outside the lab.