---
title: "Bayesian Thinking for People Analytics"
description: |
  A recommendation for a free online book on Bayesian thinking in people analytics.
preview: ./Bayesian Thinking for PA.png
author:
  - name: Luděk Stehlík
    url: https://www.linkedin.com/in/ludekstehlik/
date: 2026-09-16
categories:
  - bayesian statistics
  - people analytics
  - decision making
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
    toc_float: true
    code_folding: true
    highlight: null
---

If you are a PA professional and you don’t know about it yet, then I highly recommend to your attention a free online book, [Bayesian Thinking for People Analytics](https://bayesian-thinking.andrewmarritt.ch/){target="_blank"}, by [Andrew Marritt](https://www.linkedin.com/in/andrewmarritt/){target="_blank"}.

IMO, there are three key things that distinguish it from other similar books:

* It’s not just a technical guide to statistics/analytics, or its specific Bayesian flavour, to be more precise, but firmly embeds it within the broader decision-making framework and PA context.
* It gently and comprehensibly introduces you to the mindset and tools of Bayesians, which can make your PA life easier in many respects, and does so in a way that lets you immediately start using them in your practice.
* It gives plenty of attention to the judgement calls we face in practice: which assumptions we make, when a simpler analysis is good enough, and how to explain the results to stakeholders.

On top of that, there is a lot of practical wisdom and also fun throughout the book.

So, highly recommended - I can only wish I’d had something like that available when I was entering the field.

Thanks to Andrew for putting something like this together and sharing it with the PA community 🙏