---
title: 'Unexpected protective effect of having a good manager?'
description: |
  Imagine that your direct manager recently left your company voluntarily, and she was among those who excelled in her managerial duties. Do you think that her above-average managerial skills would make you more or less likely to leave the company in the following months?  
preview: ./mng_attrition_illustration.png    
author:
  - name: Luděk Stehlík
    url: https://www.linkedin.com/in/ludekstehlik/
date: 01-15-2025
categories:
  - people management
  - employee attrition
  - manager
  - causal analysis
  - heterogeneity
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 2
    toc_float: true
    code_folding: true
---

Until now, based on my personal experience and common sense, I would have been quite certain that it would increase the odds of a direct report's departure. After all, we like good bosses so much that we might follow them – even outside our current company, right?

So I was quite surprised when I examined a real-world dataset and checked the impact of managers' voluntary departure on employees' probability of leaving, in interaction with manager quality as measured by multi-rater feedback, while controlling for some typical organizational confounders.

As expected, a manager's departure increased the odds of an employee leaving later. However, managerial quality actually had a protective effect and decreased the employee's risk of leaving when their manager left. Interestingly, more “technical” skills – such as communicating expectations, goal setting, or providing feedback – seemed to be more important in this respect than “softer” skills – like coaching, psychological safety, or wellbeing support. 

Now, besides cross-validating the results, I am trying to understand the potential reasons (including missed confounders) behind this pattern. What would be your favorite hypotheses to test?