---
title: 'Using Doppelgänger for career pathing?'
description: |
  Exploring an idea around using counterfactual and hypothetical scenarios to help employees navigate their career options. 
preview: ./poster.jpg    
author:
  - name: Luděk Stehlík
    url: https://www.linkedin.com/in/ludekstehlik/
date: 06-20-2025
categories:
  - career pathing
  - causal inference  
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 2
    toc_float: true
    code_folding: true
---

While working with Cole Napper on an [article about causal inference in People Analytics](https://blog-about-people-analytics.netlify.app/posts/2025-05-21-causal-inference-in-people-analytics/){target="_blank"}, it came to my mind that the so-called *Doppelgänger* technique could inspire a potentially handy tool for helping employees map career options within their organization.

As many of you know, the *Doppelgänger* technique is about finding a [synthetic comparison unit](https://en.wikipedia.org/wiki/Synthetic_control_method){target="_blank"} that closely mirrors the treated unit before an intervention, enabling us to estimate what would have happened in its absence. Think of the UK and the Brexit vote, where researchers built a synthetic “Doppelgänger” economy to estimate how the country would have performed had it remained in the EU.

That got me thinking about a career pathing analytics approach inspired by (but not identical to!) this causal inference technique. Imagine that, as an employee, you had the option to (in an anonymized way) find colleagues who started around the same time and from a similar starting point—based on criteria like role, age, skills, etc. You could then compare your own career path, shaped (at least partially) by your decisions, to theirs, shaped by theirs. From that comparison, you might uncover alternative paths you haven’t taken—but potentially still could—if you'd like to steer your career in that direction.

Another option would be to include in your group of “career twins” also employees who joined the company before you, to expand the comparison set—though with a higher risk of less relevant insights, since the career landscape evolves and doesn't stay the same over time.

While I believe this type of insight could be valuable for career decisions, I’m definitely not suggesting it should be the only or even the primary input—everyone’s situation is unique, the past isn’t always the best guide to the future, and human (or perhaps non-human) creativity can always come up with something new and unexpected. I tend to think of it as an analogue to the “outside view”—a useful first step in reference-class forecasting that helps counter our natural planning fallacy before diving into project-specific details.

Curious if anyone is using this or similar techniques to systematically support employees in their career pathing. Feel free to share your experiences or ideas in the comments.

P.S. The illustrative pic is from the 1998 movie *[Sliding Doors](https://en.wikipedia.org/wiki/Sliding_Doors){target="_blank"}*, which follows two parallel timelines depending on whether the protagonist catches a subway train. If you're into “what if” stories and romcoms, you may like it 😍


